name: on-opening-issue

on:
  issues:
    types: [opened, reopened]

permissions:
  contents: read

jobs:
  add-issue-to-project:
    uses: ./.github/workflows/add-issue-to-project.yml
    secrets:
      PAT: ${{ secrets.NEURODESK_GITHUB_TOKEN_ISSUE_AUTOMATION }}
